Fix cheerio function calls within addTemplate
The addTemplate tried to call functions on this that don't exist, causing the "TypeError: undefined is not a function" error to occur.